# Generated by Django 5.2.12 on 2026-03-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('vulnerabilities', models.IntegerField(default=0)),
                ('lastScanned', models.DateTimeField(auto_now=True)),
                ('details', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalLogs', models.IntegerField(default=0)),
                ('totalAttacks', models.IntegerField(default=0)),
                ('activeThreats', models.IntegerField(default=0)),
                ('blockedIPs', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Stats',
            },
        ),
        migrations.CreateModel(
            name='ThreatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('attackType', models.CharField(max_length=100)),
                ('payload', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Blocked', 'Blocked')], max_length=50)),
                ('app', models.CharField(max_length=100)),
            ],
        ),
    ]
