# Generated by Django 5.2.12 on 2026-04-04 15:53

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SecurityScan',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='app',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='attackType',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='status',
        ),
        migrations.AddField(
            model_name='threatlog',
            name='attack_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threatlog',
            name='endpoint',
            field=models.CharField(default=datetime.datetime(2026, 4, 4, 15, 53, 23, 860910, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threatlog',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='payload',
            field=models.TextField(blank=True),
        ),
    ]
