# Generated by Django 5.2.12 on 2026-04-04 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_blockedip_delete_securityscan_delete_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatlog',
            name='target',
            field=models.CharField(default=datetime.datetime(2026, 4, 4, 16, 31, 33, 522659, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
