# Generated by Django 5.2.12 on 2026-04-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_threatlog_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatlog',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
