# Generated by Django 5.0.3 on 2026-04-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_threatlog_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatlog',
            name='attack_type',
            field=models.CharField(max_length=100),
        ),
    ]
