# Generated by Django 5.0.3 on 2026-04-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_threatlog_attack_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('SQLI', 'SQL Injection'), ('XSS', 'Cross Site Scripting'), ('DDOS', 'DDoS'), ('BRUTE', 'Brute Force')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('target', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('payload', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ThreatLog',
        ),
    ]
