# Generated by Django 5.0.3 on 2026-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_attacklog_delete_threatlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('attack_type', models.CharField(max_length=100)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('ignored', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='AttackLog',
        ),
    ]
